export const FETCH_HISTORY = 'FETCH_HISTORY';
export const FETCH_HISTORY_SUCCESS = 'FETCH_HISTORY_SUCCESS';
export const FETCH_HISTORY_FAILURE = 'FETCH_HISTORY_FAILURE';

export const FETCH_HISTORIC_EVENT = 'FETCH_HISTORIC_EVENT';
export const FETCH_HISTORIC_EVENT_SUCCESS = 'FETCH_HISTORIC_EVENT_SUCCESS';
export const FETCH_HISTORIC_EVENT_FAILURE = 'FETCH_HISTORIC_EVENT_FAILURE';
